"""empty message

Revision ID: d1de2c56fe0
Revises: 277d17eb936f
Create Date: 2014-02-21 20:08:03.333145

"""

# revision identifiers, used by Alembic.
revision = 'd1de2c56fe0'
down_revision = '277d17eb936f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('principles_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principle_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['principle_id'], ['principle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('principles_translation')
    op.drop_table('principle')
    ### end Alembic commands ###
